---
galaxy_info:
  author: Lorenzo Pisani
  description: Role for provisioning the OpenVPN Server software
  license: MIT
  min_ansible_version: 1.2
  platforms:
    - name: Ubuntu
      versions:
        - trusty
  categories:
    - system
dependencies: []
